# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "github Test"
  lane :call_url do
    sh("curl -sb --location --request GET https://fjs53x6w0g.execute-api.us-east-1.amazonaws.com/Stage/country > ~/response.json")
  end
end
